<?php

// This file was generated by liblab | https://liblab.com/

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use WellSyncServicesCareConnect\Models;

use WellSyncServicesCareConnect\Client;

$sdk = new Client(accessToken: 'YOUR_TOKEN');

$response = $sdk->pharmacy->pharmacyReEnqueuePrescription(prescriptionId: 'prescriptionId');

print_r($response);
