<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Services;

use WellSyncServicesCareConnect\Utils\Serializer;
use WellSyncServicesCareConnect\Models;

class BillingServices extends BaseService
{
    public function billingServicesGetAccountManagement(string $clinicId): Models\GetAccountManagementResponse
    {
        $data = $this->sendRequest('get', "/v1/billing-account/{$clinicId}", []);

        return Serializer::deserialize($data, Models\GetAccountManagementResponse::class);
    }

    public function billingServicesGetClinicAccountValidity(string $clinicId): Models\GetClinicAccountValidityResponse
    {
        $data = $this->sendRequest('get', "/v1/billing-account/{$clinicId}/valid", []);

        return Serializer::deserialize($data, Models\GetClinicAccountValidityResponse::class);
    }

    public function billingServicesUpdateDrugPricesForClinic(
        Models\BillingServicesUpdateDrugPricesForClinicRequest $input,
        string $clinicId
    ): array {
        $data = $this->sendRequest('put', "/v1/clinics/{$clinicId}/drug_prices", [
            'json' => Serializer::serialize($input),
        ]);

        return json_decode($data, true);
    }

    public function billingServicesGetClinicTier(string $clinicId): Models\GetClinicTierResponse
    {
        $data = $this->sendRequest('get', "/v1/clinics/{$clinicId}/tier", []);

        return Serializer::deserialize($data, Models\GetClinicTierResponse::class);
    }

    public function billingServicesSetClinicTier(
        Models\BillingServicesSetClinicTierRequest $input,
        string $clinicId
    ): array {
        $data = $this->sendRequest('put', "/v1/clinics/{$clinicId}/tier", ['json' => Serializer::serialize($input)]);

        return json_decode($data, true);
    }

    public function billingServicesGetPricesForClinic(string $clinicId = null): Models\GetPricesForClinicResponse
    {
        $data = $this->sendRequest('get', '/v1/prices', [
            'query' => [
                'clinicId' => $clinicId,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetPricesForClinicResponse::class);
    }

    public function billingServicesGetTiers(): Models\GetTiersResponse
    {
        $data = $this->sendRequest('get', '/v1/tiers', []);

        return Serializer::deserialize($data, Models\GetTiersResponse::class);
    }
}
