<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Services;

use WellSyncServicesCareConnect\Utils\Serializer;
use WellSyncServicesCareConnect\Models;

class Sessions extends BaseService
{
    /**
     * Creates a new session using the given API key for the given scope
     */
    public function createSession(?array $input = null): Models\Session
    {
        $data = $this->sendRequest('post', '/v1/sessions', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\Session::class);
    }
}
