<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Services;

use WellSyncServicesCareConnect\Utils\Serializer;
use WellSyncServicesCareConnect\Models;

class Tokens extends BaseService
{
    /**
     * Lists all API tokens for a specific clinic
     */
    public function listClinicApiTokens(string $clinicId): array
    {
        $data = $this->sendRequest('get', "/v1/clinics/{$clinicId}/api-tokens", []);

        return json_decode($data, true);
    }

    /**
     * Creates a new API token for a specific clinic
     */
    public function createClinicApiToken(Models\CreateTokenRequest $input, string $clinicId): Models\PlainToken
    {
        $data = $this->sendRequest('post', "/v1/clinics/{$clinicId}/api-tokens", [
            'json' => Serializer::serialize($input),
        ]);

        return Serializer::deserialize($data, Models\PlainToken::class);
    }

    /**
     * Deletes a specific API token for a clinic
     */
    public function deleteClinicApiToken(string $clinicId, string $tokenId): mixed
    {
        $data = $this->sendRequest('delete', "/v1/clinics/{$clinicId}/api-tokens/{$tokenId}", []);

        return json_decode($data, true);
    }
}
