<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class AddPublicKeyResponse
{
    #[SerializedName('publicKey')]
    public ?PublicKey $publicKey;

    public function __construct(?PublicKey $publicKey = null)
    {
        $this->publicKey = $publicKey;
    }
}
