<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Address
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('addressLineOne')]
    public ?string $addressLineOne;

    #[SerializedName('addressLineTwo')]
    public ?string $addressLineTwo;

    #[SerializedName('city')]
    public ?string $city;

    #[SerializedName('zip')]
    public ?string $zip;

    #[SerializedName('administrativeArea')]
    public ?string $administrativeArea;

    #[SerializedName('country')]
    public ?string $country;

    #[SerializedName('archived')]
    public ?bool $archived;

    /**
     * Description is an optional string that may be set by the user to describe the address (e.g. "home" or "office")
     */
    #[SerializedName('description')]
    public ?string $description;

    public function __construct(
        ?string $id = null,
        ?string $addressLineOne = null,
        ?string $addressLineTwo = null,
        ?string $city = null,
        ?string $zip = null,
        ?string $administrativeArea = null,
        ?string $country = null,
        ?bool $archived = null,
        ?string $description = null
    ) {
        $this->id = $id;
        $this->addressLineOne = $addressLineOne;
        $this->addressLineTwo = $addressLineTwo;
        $this->city = $city;
        $this->zip = $zip;
        $this->administrativeArea = $administrativeArea;
        $this->country = $country;
        $this->archived = $archived;
        $this->description = $description;
    }
}
