<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class AddUserResponse
{
    #[SerializedName('userId')]
    public ?string $userId;

    #[SerializedName('identityRecovery')]
    public ?IdentityRecovery $identityRecovery;

    public function __construct(?string $userId = null, ?IdentityRecovery $identityRecovery = null)
    {
        $this->userId = $userId;
        $this->identityRecovery = $identityRecovery;
    }
}
