<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class AddUserRequest
{
    #[SerializedName('firstName')]
    public ?string $firstName;

    #[SerializedName('lastName')]
    public ?string $lastName;

    #[SerializedName('email')]
    public ?string $email;

    #[SerializedName('phone')]
    public ?string $phone;

    /**
     * @var string[]|null
     * Roles to assign to the user. This can include predefined roles like 'admin', 'subtenant-admin', 'agent', custom roles like 'clinician:<clinic_id>'are derived from the clinics assigned to the user.
     */
    #[SerializedName('roles')]
    public ?array $roles;

    /**
     * @var ClinicMembership[]|null
     * List of clinics and roles the user is associated with. This allows for more granular control over user permissions within specific clinics.
     */
    #[SerializedName('clinicMemberships')]
    public ?array $clinicMemberships;

    public function __construct(
        ?string $firstName = null,
        ?string $lastName = null,
        ?string $email = null,
        ?string $phone = null,
        ?array $roles = [],
        ?array $clinicMemberships = []
    ) {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->phone = $phone;
        $this->roles = $roles;
        $this->clinicMemberships = $clinicMemberships;
    }
}
