<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class BillingServicesUpdateDrugPricesForClinicRequest
{
    /**
     * @var DrugPrice[]|null
     */
    #[SerializedName('drugPrices')]
    public ?array $drugPrices;

    public function __construct(?array $drugPrices = [])
    {
        $this->drugPrices = $drugPrices;
    }
}
