<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ClinicMembership
{
    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('role')]
    public ?string $role;

    public function __construct(?string $clinicId = null, ?string $role = null)
    {
        $this->clinicId = $clinicId;
        $this->role = $role;
    }
}
