<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ConvenienceFee
{
    #[SerializedName('tenant')]
    public ?string $tenant;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('feePercentage')]
    public ?float $feePercentage;

    public function __construct(?string $tenant = null, ?string $clinicId = null, ?float $feePercentage = null)
    {
        $this->tenant = $tenant;
        $this->clinicId = $clinicId;
        $this->feePercentage = $feePercentage;
    }
}
