<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateClinicianResponse
{
    #[SerializedName('clinician')]
    public ?Clinician $clinician;

    #[SerializedName('identityRecovery')]
    public ?IdentityRecovery $identityRecovery;

    public function __construct(?Clinician $clinician = null, ?IdentityRecovery $identityRecovery = null)
    {
        $this->clinician = $clinician;
        $this->identityRecovery = $identityRecovery;
    }
}
