<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateAddressForTenantResponse
{
    #[SerializedName('addressId')]
    public ?string $addressId;

    public function __construct(?string $addressId = null)
    {
        $this->addressId = $addressId;
    }
}
