<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateTokenRequest
{
    /**
     * Human-readable name for the token
     */
    #[SerializedName('name')]
    public string $name;

    /**
     * Optional description of the token's purpose
     */
    #[SerializedName('description')]
    public ?string $description;

    public function __construct(string $name, ?string $description = null)
    {
        $this->name = $name;
        $this->description = $description;
    }
}
