<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateClinicianRequest
{
    #[SerializedName('clinician')]
    public ?Clinician $clinician;

    /**
     * @var string[]|null
     */
    #[SerializedName('clinicIds')]
    public ?array $clinicIds;

    /**
     * if set a identity account is created for the given clinician and a identity recovery link is returned
     */
    #[SerializedName('createIdentity')]
    public ?bool $createIdentity;

    public function __construct(?Clinician $clinician = null, ?array $clinicIds = [], ?bool $createIdentity = null)
    {
        $this->clinician = $clinician;
        $this->clinicIds = $clinicIds;
        $this->createIdentity = $createIdentity;
    }
}
