<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreatePatientResponse
{
    #[SerializedName('patientId')]
    public ?string $patientId;

    public function __construct(?string $patientId = null)
    {
        $this->patientId = $patientId;
    }
}
