<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum DosageForms: string
{
    case Unspecified = 'Unspecified';
    case Injectable = 'Injectable';
    case Odt = 'ODT';
    case Tablet = 'Tablet';
    case Capsule = 'Capsule';
    case Cream = 'Cream';
    case Troche = 'Troche';
}
