<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Dosage
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('concentration')]
    public ?string $concentration;

    #[SerializedName('defaultQuantity')]
    public ?int $defaultQuantity;

    #[SerializedName('concentrationLvl')]
    public ?int $concentrationLvl;

    #[SerializedName('directions')]
    public ?string $directions;

    #[SerializedName('minQuantity')]
    public ?int $minQuantity;

    #[SerializedName('maxQuantity')]
    public ?int $maxQuantity;

    #[SerializedName('quantityStep')]
    public ?int $quantityStep;

    /**
     * @var ShippingMethods[]|null
     */
    #[SerializedName('shippingMethods')]
    public ?array $shippingMethods;

    #[SerializedName('volume')]
    public ?int $volume;

    public function __construct(
        ?string $id = null,
        ?string $concentration = null,
        ?int $defaultQuantity = null,
        ?int $concentrationLvl = null,
        ?string $directions = null,
        ?int $minQuantity = null,
        ?int $maxQuantity = null,
        ?int $quantityStep = null,
        ?array $shippingMethods = [],
        ?int $volume = null
    ) {
        $this->id = $id;
        $this->concentration = $concentration;
        $this->defaultQuantity = $defaultQuantity;
        $this->concentrationLvl = $concentrationLvl;
        $this->directions = $directions;
        $this->minQuantity = $minQuantity;
        $this->maxQuantity = $maxQuantity;
        $this->quantityStep = $quantityStep;
        $this->shippingMethods = $shippingMethods;
        $this->volume = $volume;
    }
}
