<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Drug
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('dosageForm')]
    public ?DosageForm $dosageForm;

    /**
     * @var Dosage[]|null
     */
    #[SerializedName('dosages')]
    public ?array $dosages;

    #[SerializedName('ndc')]
    public ?string $ndc;

    /**
     * @var AllowedShippingMethods[]|null
     */
    #[SerializedName('allowedShippingMethods')]
    public ?array $allowedShippingMethods;

    #[SerializedName('isMedicallyDifferent')]
    public ?bool $isMedicallyDifferent;

    public function __construct(
        ?string $id = null,
        ?string $name = null,
        ?DosageForm $dosageForm = null,
        ?array $dosages = [],
        ?string $ndc = null,
        ?array $allowedShippingMethods = [],
        ?bool $isMedicallyDifferent = null
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->dosageForm = $dosageForm;
        $this->dosages = $dosages;
        $this->ndc = $ndc;
        $this->allowedShippingMethods = $allowedShippingMethods;
        $this->isMedicallyDifferent = $isMedicallyDifferent;
    }
}
