<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class DrugPrice
{
    #[SerializedName('tenant')]
    public ?string $tenant;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('drugId')]
    public ?string $drugId;

    #[SerializedName('dosageId')]
    public ?string $dosageId;

    #[SerializedName('price')]
    public ?float $price;

    #[SerializedName('tier')]
    public ?string $tier;

    public function __construct(
        ?string $tenant = null,
        ?string $clinicId = null,
        ?string $drugId = null,
        ?string $dosageId = null,
        ?float $price = null,
        ?string $tier = null
    ) {
        $this->tenant = $tenant;
        $this->clinicId = $clinicId;
        $this->drugId = $drugId;
        $this->dosageId = $dosageId;
        $this->price = $price;
        $this->tier = $tier;
    }
}
