<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetAgentsResponse
{
    #[SerializedName('pagination')]
    public ?PaginationResponse $pagination;

    /**
     * @var User[]|null
     */
    #[SerializedName('agents')]
    public ?array $agents;

    public function __construct(?PaginationResponse $pagination = null, ?array $agents = [])
    {
        $this->pagination = $pagination;
        $this->agents = $agents;
    }
}
