<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetAllowedOrderShippingMethodsResponse
{
    /**
     * @var ShippingFee[]|null
     */
    #[SerializedName('shippingFees')]
    public ?array $shippingFees;

    public function __construct(?array $shippingFees = [])
    {
        $this->shippingFees = $shippingFees;
    }
}
