<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetAccountManagementResponse
{
    #[SerializedName('hostedLoginToken')]
    public ?string $hostedLoginToken;

    #[SerializedName('hasBillingInfo')]
    public ?bool $hasBillingInfo;

    public function __construct(?string $hostedLoginToken = null, ?bool $hasBillingInfo = null)
    {
        $this->hostedLoginToken = $hostedLoginToken;
        $this->hasBillingInfo = $hasBillingInfo;
    }
}
