<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetAllDosageFormsResponse
{
    /**
     * @var DosageForms[]|null
     */
    #[SerializedName('dosageForms')]
    public ?array $dosageForms;

    public function __construct(?array $dosageForms = [])
    {
        $this->dosageForms = $dosageForms;
    }
}
