<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetClinicAccountValidityResponse
{
    #[SerializedName('isValid')]
    public ?bool $isValid;

    public function __construct(?bool $isValid = null)
    {
        $this->isValid = $isValid;
    }
}
