<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetCurrentAgentCliniciansResponse
{
    /**
     * @var Clinician[]|null
     */
    #[SerializedName('clinicians')]
    public ?array $clinicians;

    public function __construct(?array $clinicians = [])
    {
        $this->clinicians = $clinicians;
    }
}
