<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetClinicTierResponse
{
    #[SerializedName('tier')]
    public ?string $tier;

    public function __construct(?string $tier = null)
    {
        $this->tier = $tier;
    }
}
