<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetCurrentUserResponse
{
    #[SerializedName('user')]
    public ?User $user;

    public function __construct(?User $user = null)
    {
        $this->user = $user;
    }
}
