<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetClinicianResponse
{
    #[SerializedName('clinician')]
    public ?Clinician $clinician;

    /**
     * @var Clinic[]|null
     */
    #[SerializedName('clinics')]
    public ?array $clinics;

    /**
     * @var User[]|null
     */
    #[SerializedName('agents')]
    public ?array $agents;

    public function __construct(?Clinician $clinician = null, ?array $clinics = [], ?array $agents = [])
    {
        $this->clinician = $clinician;
        $this->clinics = $clinics;
        $this->agents = $agents;
    }
}
