<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetDrugsResponse
{
    /**
     * @var Drug[]|null
     */
    #[SerializedName('drugs')]
    public ?array $drugs;

    public function __construct(?array $drugs = [])
    {
        $this->drugs = $drugs;
    }
}
