<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPharmaciesResponse
{
    /**
     * @var PharmacyContactInfo[]|null
     */
    #[SerializedName('pharmacies')]
    public ?array $pharmacies;

    public function __construct(?array $pharmacies = [])
    {
        $this->pharmacies = $pharmacies;
    }
}
