<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPatientsResponse
{
    /**
     * @var Patient[]|null
     */
    #[SerializedName('patients')]
    public ?array $patients;

    #[SerializedName('pagination')]
    public ?PaginationResponse $pagination;

    public function __construct(?array $patients = [], ?PaginationResponse $pagination = null)
    {
        $this->patients = $patients;
        $this->pagination = $pagination;
    }
}
