<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPublicKeysResponse
{
    /**
     * @var PublicKey[]|null
     */
    #[SerializedName('publicKeys')]
    public ?array $publicKeys;

    public function __construct(?array $publicKeys = [])
    {
        $this->publicKeys = $publicKeys;
    }
}
