<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPricesForClinicResponse
{
    /**
     * @var DrugPrice[]|null
     */
    #[SerializedName('drugPrices')]
    public ?array $drugPrices;

    /**
     * @var ShippingFee[]|null
     */
    #[SerializedName('shippingFees')]
    public ?array $shippingFees;

    #[SerializedName('creditCardFee')]
    public ?ConvenienceFee $creditCardFee;

    #[SerializedName('convenienceFee')]
    public ?ConvenienceFee $convenienceFee;

    public function __construct(
        ?array $drugPrices = [],
        ?array $shippingFees = [],
        ?ConvenienceFee $creditCardFee = null,
        ?ConvenienceFee $convenienceFee = null
    ) {
        $this->drugPrices = $drugPrices;
        $this->shippingFees = $shippingFees;
        $this->creditCardFee = $creditCardFee;
        $this->convenienceFee = $convenienceFee;
    }
}
