<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPharmacyByDrugResponse
{
    #[SerializedName('pharmacy')]
    public ?PharmacyContactInfo $pharmacy;

    public function __construct(?PharmacyContactInfo $pharmacy = null)
    {
        $this->pharmacy = $pharmacy;
    }
}
