<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPrescriptionsResponse
{
    /**
     * @var Prescription[]|null
     */
    #[SerializedName('prescriptions')]
    public ?array $prescriptions;

    #[SerializedName('pagination')]
    public ?PaginationResponse $pagination;

    public function __construct(?array $prescriptions = [], ?PaginationResponse $pagination = null)
    {
        $this->prescriptions = $prescriptions;
        $this->pagination = $pagination;
    }
}
