<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPrescriptionItemResponse
{
    #[SerializedName('prescriptionItem')]
    public ?PrescriptionItem $prescriptionItem;

    public function __construct(?PrescriptionItem $prescriptionItem = null)
    {
        $this->prescriptionItem = $prescriptionItem;
    }
}
