<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPrescriptionItemsResponse
{
    /**
     * @var PrescriptionItem[]|null
     */
    #[SerializedName('prescriptionItems')]
    public ?array $prescriptionItems;

    #[SerializedName('pagination')]
    public ?PaginationResponse $pagination;

    public function __construct(?array $prescriptionItems = [], ?PaginationResponse $pagination = null)
    {
        $this->prescriptionItems = $prescriptionItems;
        $this->pagination = $pagination;
    }
}
