<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetTiersResponse
{
    /**
     * @var string[]|null
     */
    #[SerializedName('tiers')]
    public ?array $tiers;

    public function __construct(?array $tiers = [])
    {
        $this->tiers = $tiers;
    }
}
