<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetUserClinicsResponse
{
    /**
     * @var Clinic[]|null
     */
    #[SerializedName('clinics')]
    public ?array $clinics;

    public function __construct(?array $clinics = [])
    {
        $this->clinics = $clinics;
    }
}
