<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetUserIdentityRecoveryLinkResponse
{
    #[SerializedName('identityRecovery')]
    public ?IdentityRecovery $identityRecovery;

    public function __construct(?IdentityRecovery $identityRecovery = null)
    {
        $this->identityRecovery = $identityRecovery;
    }
}
