<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetUsersResponse
{
    /**
     * @var User[]|null
     */
    #[SerializedName('users')]
    public ?array $users;

    #[SerializedName('pagination')]
    public ?PaginationResponse $pagination;

    public function __construct(?array $users = [], ?PaginationResponse $pagination = null)
    {
        $this->users = $users;
        $this->pagination = $pagination;
    }
}
