<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Height
{
    #[SerializedName('cm')]
    public ?float $cm;

    #[SerializedName('feet')]
    public ?float $feet;

    #[SerializedName('inches')]
    public ?float $inches;

    public function __construct(?float $cm = null, ?float $feet = null, ?float $inches = null)
    {
        $this->cm = $cm;
        $this->feet = $feet;
        $this->inches = $inches;
    }
}
