<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class IdentityRecovery
{
    #[SerializedName('link')]
    public ?string $link;

    #[SerializedName('code')]
    public ?string $code;

    #[SerializedName('expiresAt')]
    public ?string $expiresAt;

    public function __construct(?string $link = null, ?string $code = null, ?string $expiresAt = null)
    {
        $this->link = $link;
        $this->code = $code;
        $this->expiresAt = $expiresAt;
    }
}
