<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class LineItem
{
    #[SerializedName('drugId')]
    public ?string $drugId;

    #[SerializedName('dosageId')]
    public ?string $dosageId;

    #[SerializedName('quantity')]
    public ?int $quantity;

    public function __construct(?string $drugId = null, ?string $dosageId = null, ?int $quantity = null)
    {
        $this->drugId = $drugId;
        $this->dosageId = $dosageId;
        $this->quantity = $quantity;
    }
}
