<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class LineItemPreview
{
    #[SerializedName('drugId')]
    public ?string $drugId;

    #[SerializedName('dosageId')]
    public ?string $dosageId;

    #[SerializedName('quantity')]
    public ?int $quantity;

    #[SerializedName('price')]
    public ?float $price;

    public function __construct(
        ?string $drugId = null,
        ?string $dosageId = null,
        ?int $quantity = null,
        ?float $price = null
    ) {
        $this->drugId = $drugId;
        $this->dosageId = $dosageId;
        $this->quantity = $quantity;
        $this->price = $price;
    }
}
