<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Order
{
    /**
     * unique identifier in pharmacy hub
     */
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('patientId')]
    public ?string $patientId;

    /**
     * external_case_id is an optional field that could be used to identify an order using an external identifier.
     */
    #[SerializedName('externalCaseId')]
    public ?string $externalCaseId;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('clinicianId')]
    public ?string $clinicianId;

    #[SerializedName('agentId')]
    public ?string $agentId;

    #[SerializedName('shippingMethod')]
    public ?OrderShippingMethod $shippingMethod;

    #[SerializedName('shippingAddress')]
    public ?Address $shippingAddress;

    /**
     * @var Prescription[]|null
     */
    #[SerializedName('prescriptions')]
    public ?array $prescriptions;

    #[SerializedName('createdAt')]
    public ?string $createdAt;

    #[SerializedName('updatedAt')]
    public ?string $updatedAt;

    public function __construct(
        ?string $id = null,
        ?string $patientId = null,
        ?string $externalCaseId = null,
        ?string $clinicId = null,
        ?string $clinicianId = null,
        ?string $agentId = null,
        ?OrderShippingMethod $shippingMethod = null,
        ?Address $shippingAddress = null,
        ?array $prescriptions = [],
        ?string $createdAt = null,
        ?string $updatedAt = null
    ) {
        $this->id = $id;
        $this->patientId = $patientId;
        $this->externalCaseId = $externalCaseId;
        $this->clinicId = $clinicId;
        $this->clinicianId = $clinicianId;
        $this->agentId = $agentId;
        $this->shippingMethod = $shippingMethod;
        $this->shippingAddress = $shippingAddress;
        $this->prescriptions = $prescriptions;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}
