<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PaginationResponse
{
    #[SerializedName('size')]
    public ?int $size;

    #[SerializedName('page')]
    public ?int $page;

    #[SerializedName('total')]
    public ?int $total;

    public function __construct(?int $size = null, ?int $page = null, ?int $total = null)
    {
        $this->size = $size;
        $this->page = $page;
        $this->total = $total;
    }
}
