<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Patient
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('email')]
    public ?string $email;

    /**
     * Patients phone number in E.164 format
     */
    #[SerializedName('phone')]
    public ?string $phone;

    #[SerializedName('firstName')]
    public ?string $firstName;

    #[SerializedName('lastName')]
    public ?string $lastName;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('addressLineOne')]
    public ?string $addressLineOne;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('addressLineTwo')]
    public ?string $addressLineTwo;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('city')]
    public ?string $city;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('zip')]
    public ?string $zip;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('administrativeArea')]
    public ?string $administrativeArea;

    /**
     * DEPRECATED: refer to the primary address. Setting this value in an update will have no effect.
     */
    #[SerializedName('country')]
    public ?string $country;

    #[SerializedName('dateOfBirth')]
    public ?string $dateOfBirth;

    #[SerializedName('profile')]
    public ?PatientProfile $profile;

    #[SerializedName('tenantId')]
    public ?string $tenantId;

    #[SerializedName('externalId')]
    public ?string $externalId;

    /**
     * @var Address[]|null
     * All addresses for this patient. Read-only, setting this value in an update will have no effect.
     */
    #[SerializedName('addresses')]
    public ?array $addresses;

    /**
     * The primary address ID for this patient. May be set in an update to change the primary address.
     */
    #[SerializedName('primaryAddressId')]
    public ?string $primaryAddressId;

    #[SerializedName('primaryAddress')]
    public ?Address $primaryAddress;

    #[SerializedName('internalEmail')]
    public ?string $internalEmail;

    /**
	 * The sub-tenant ID for this patient it is used for sub-tenants
 like a clinic for ola to prescribe prescriptions
	 */
    #[SerializedName('subTenantId')]
    public ?string $subTenantId;

    public function __construct(
        ?string $id = null,
        ?string $email = null,
        ?string $phone = null,
        ?string $firstName = null,
        ?string $lastName = null,
        ?string $addressLineOne = null,
        ?string $addressLineTwo = null,
        ?string $city = null,
        ?string $zip = null,
        ?string $administrativeArea = null,
        ?string $country = null,
        ?string $dateOfBirth = null,
        ?PatientProfile $profile = null,
        ?string $tenantId = null,
        ?string $externalId = null,
        ?array $addresses = [],
        ?string $primaryAddressId = null,
        ?Address $primaryAddress = null,
        ?string $internalEmail = null,
        ?string $subTenantId = null
    ) {
        $this->id = $id;
        $this->email = $email;
        $this->phone = $phone;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->addressLineOne = $addressLineOne;
        $this->addressLineTwo = $addressLineTwo;
        $this->city = $city;
        $this->zip = $zip;
        $this->administrativeArea = $administrativeArea;
        $this->country = $country;
        $this->dateOfBirth = $dateOfBirth;
        $this->profile = $profile;
        $this->tenantId = $tenantId;
        $this->externalId = $externalId;
        $this->addresses = $addresses;
        $this->primaryAddressId = $primaryAddressId;
        $this->primaryAddress = $primaryAddress;
        $this->internalEmail = $internalEmail;
        $this->subTenantId = $subTenantId;
    }
}
