<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatientProfile
{
    #[SerializedName('height')]
    public ?Height $height;

    #[SerializedName('weight')]
    public ?Weight $weight;

    /**
     * @var string[]|null
     */
    #[SerializedName('allergies')]
    public ?array $allergies;

    /**
     * @var string[]|null
     */
    #[SerializedName('medicalConditions')]
    public ?array $medicalConditions;

    #[SerializedName('bpSystolic')]
    public ?int $bpSystolic;

    #[SerializedName('bpDiastolic')]
    public ?int $bpDiastolic;

    #[SerializedName('heartRate')]
    public ?int $heartRate;

    /**
     * @var string[]|null
     */
    #[SerializedName('medications')]
    public ?array $medications;

    #[SerializedName('sexAtBirth')]
    public ?SexAtBirth $sexAtBirth;

    public function __construct(
        ?Height $height = null,
        ?Weight $weight = null,
        ?array $allergies = [],
        ?array $medicalConditions = [],
        ?int $bpSystolic = null,
        ?int $bpDiastolic = null,
        ?int $heartRate = null,
        ?array $medications = [],
        ?SexAtBirth $sexAtBirth = null
    ) {
        $this->height = $height;
        $this->weight = $weight;
        $this->allergies = $allergies;
        $this->medicalConditions = $medicalConditions;
        $this->bpSystolic = $bpSystolic;
        $this->bpDiastolic = $bpDiastolic;
        $this->heartRate = $heartRate;
        $this->medications = $medications;
        $this->sexAtBirth = $sexAtBirth;
    }
}
