<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyAddUserRolesRequest
{
    /**
     * @var string[]|null
     */
    #[SerializedName('roles')]
    public ?array $roles;

    public function __construct(?array $roles = [])
    {
        $this->roles = $roles;
    }
}
