<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyLinkAgentToClinicianRequest
{
    #[SerializedName('agentId')]
    public ?string $agentId;

    public function __construct(?string $agentId = null)
    {
        $this->agentId = $agentId;
    }
}
