<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacySubmitExternalOrderRequest
{
    /**
     * external_case_id is used to identify the order in external systems
     */
    #[SerializedName('externalCaseId')]
    public ?string $externalCaseId;

    /**
     * symmetrical_signing_key is provided to sign the order
     */
    #[SerializedName('symmetricalSigningKey')]
    public ?string $symmetricalSigningKey;

    #[SerializedName('patient')]
    public ?Patient $patient;

    #[SerializedName('clinician')]
    public ?Clinician $clinician;

    #[SerializedName('shippingMethod')]
    public ?PharmacySubmitExternalOrderRequestShippingMethod $shippingMethod;

    #[SerializedName('shippingAddress')]
    public ?Address $shippingAddress;

    /**
     * @var PrescriptionItem[]|null
     */
    #[SerializedName('prescriptionItems')]
    public ?array $prescriptionItems;

    public function __construct(
        ?string $externalCaseId = null,
        ?string $symmetricalSigningKey = null,
        ?Patient $patient = null,
        ?Clinician $clinician = null,
        ?PharmacySubmitExternalOrderRequestShippingMethod $shippingMethod = null,
        ?Address $shippingAddress = null,
        ?array $prescriptionItems = []
    ) {
        $this->externalCaseId = $externalCaseId;
        $this->symmetricalSigningKey = $symmetricalSigningKey;
        $this->patient = $patient;
        $this->clinician = $clinician;
        $this->shippingMethod = $shippingMethod;
        $this->shippingAddress = $shippingAddress;
        $this->prescriptionItems = $prescriptionItems;
    }
}
