<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyUpdateClinicRequest
{
    #[SerializedName('addressLineOne')]
    public ?string $addressLineOne;

    #[SerializedName('addressLineTwo')]
    public ?string $addressLineTwo;

    #[SerializedName('city')]
    public ?string $city;

    #[SerializedName('zip')]
    public ?string $zip;

    #[SerializedName('administrativeArea')]
    public ?string $administrativeArea;

    #[SerializedName('country')]
    public ?string $country;

    #[SerializedName('phone')]
    public ?string $phone;

    /**
     * The name of the clinic
     */
    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('salesRep')]
    public ?string $salesRep;

    public function __construct(
        ?string $addressLineOne = null,
        ?string $addressLineTwo = null,
        ?string $city = null,
        ?string $zip = null,
        ?string $administrativeArea = null,
        ?string $country = null,
        ?string $phone = null,
        ?string $name = null,
        ?string $salesRep = null
    ) {
        $this->addressLineOne = $addressLineOne;
        $this->addressLineTwo = $addressLineTwo;
        $this->city = $city;
        $this->zip = $zip;
        $this->administrativeArea = $administrativeArea;
        $this->country = $country;
        $this->phone = $phone;
        $this->name = $name;
        $this->salesRep = $salesRep;
    }
}
