<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyContactInfo
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('email')]
    public ?string $email;

    #[SerializedName('phone')]
    public ?string $phone;

    #[SerializedName('fax')]
    public ?string $fax;

    #[SerializedName('addressLineOne')]
    public ?string $addressLineOne;

    #[SerializedName('addressLineTwo')]
    public ?string $addressLineTwo;

    #[SerializedName('city')]
    public ?string $city;

    #[SerializedName('administrativeArea')]
    public ?string $administrativeArea;

    #[SerializedName('zip')]
    public ?string $zip;

    public function __construct(
        ?string $id = null,
        ?string $name = null,
        ?string $email = null,
        ?string $phone = null,
        ?string $fax = null,
        ?string $addressLineOne = null,
        ?string $addressLineTwo = null,
        ?string $city = null,
        ?string $administrativeArea = null,
        ?string $zip = null
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->email = $email;
        $this->phone = $phone;
        $this->fax = $fax;
        $this->addressLineOne = $addressLineOne;
        $this->addressLineTwo = $addressLineTwo;
        $this->city = $city;
        $this->administrativeArea = $administrativeArea;
        $this->zip = $zip;
    }
}
