<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyUpdateUserRequest
{
    #[SerializedName('firstName')]
    public ?string $firstName;

    #[SerializedName('lastName')]
    public ?string $lastName;

    public function __construct(?string $firstName = null, ?string $lastName = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
    }
}
