<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacySubmitPrescriptionRequest
{
    #[SerializedName('externalCaseId')]
    public ?string $externalCaseId;

    #[SerializedName('prescription')]
    public ?Prescription $prescription;

    public function __construct(?string $externalCaseId = null, ?Prescription $prescription = null)
    {
        $this->externalCaseId = $externalCaseId;
        $this->prescription = $prescription;
    }
}
