<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyPreviewOrderSummaryRequest
{
    #[SerializedName('state')]
    public ?string $state;

    /**
     * @var LineItem[]|null
     */
    #[SerializedName('lineItems')]
    public ?array $lineItems;

    #[SerializedName('shippingMethod')]
    public ?PharmacyPreviewOrderSummaryRequestShippingMethod $shippingMethod;

    public function __construct(
        ?string $state = null,
        ?array $lineItems = [],
        ?PharmacyPreviewOrderSummaryRequestShippingMethod $shippingMethod = null
    ) {
        $this->state = $state;
        $this->lineItems = $lineItems;
        $this->shippingMethod = $shippingMethod;
    }
}
