<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyAddPublicKeyRequest
{
    #[SerializedName('pem')]
    public ?string $pem;

    #[SerializedName('alias')]
    public ?string $alias;

    public function __construct(?string $pem = null, ?string $alias = null)
    {
        $this->pem = $pem;
        $this->alias = $alias;
    }
}
