<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacySubmitClinicianOrderRequest
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('externalCaseId')]
    public ?string $externalCaseId;

    #[SerializedName('clinicianId')]
    public ?string $clinicianId;

    #[SerializedName('agentId')]
    public ?string $agentId;

    #[SerializedName('shippingMethod')]
    public ?PharmacySubmitClinicianOrderRequestShippingMethod $shippingMethod;

    #[SerializedName('shippingAddress')]
    public ?Address $shippingAddress;

    /**
     * @var PrescriptionItem[]|null
     */
    #[SerializedName('prescriptionItems')]
    public ?array $prescriptionItems;

    #[SerializedName('signedMessage')]
    public ?string $signedMessage;

    public function __construct(
        ?string $id = null,
        ?string $externalCaseId = null,
        ?string $clinicianId = null,
        ?string $agentId = null,
        ?PharmacySubmitClinicianOrderRequestShippingMethod $shippingMethod = null,
        ?Address $shippingAddress = null,
        ?array $prescriptionItems = [],
        ?string $signedMessage = null
    ) {
        $this->id = $id;
        $this->externalCaseId = $externalCaseId;
        $this->clinicianId = $clinicianId;
        $this->agentId = $agentId;
        $this->shippingMethod = $shippingMethod;
        $this->shippingAddress = $shippingAddress;
        $this->prescriptionItems = $prescriptionItems;
        $this->signedMessage = $signedMessage;
    }
}
