<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum PharmacySubmitExternalOrderRequestShippingMethod: string
{
    case ShippingMethodUnspecified = 'SHIPPING_METHOD_UNSPECIFIED';
    case ShippingMethodStandard = 'SHIPPING_METHOD_STANDARD';
    case ShippingMethodOvernight = 'SHIPPING_METHOD_OVERNIGHT';
    case ShippingMethod2Day = 'SHIPPING_METHOD_2DAY';
    case ShippingMethod3Day = 'SHIPPING_METHOD_3DAY';
}
