<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PharmacyUpdateClinicianRequest
{
    #[SerializedName('firstName')]
    public ?string $firstName;

    #[SerializedName('lastName')]
    public ?string $lastName;

    #[SerializedName('npi')]
    public ?string $npi;

    #[SerializedName('dea')]
    public ?string $dea;

    public function __construct(
        ?string $firstName = null,
        ?string $lastName = null,
        ?string $npi = null,
        ?string $dea = null
    ) {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->npi = $npi;
        $this->dea = $dea;
    }
}
