<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PlainToken
{
    /**
     * The plaintext token - only returned once upon creation
     */
    #[SerializedName('token')]
    public string $token;

    public function __construct(string $token)
    {
        $this->token = $token;
    }
}
