<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Prescription
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('patientId')]
    public ?string $patientId;

    #[SerializedName('pharmacyId')]
    public ?string $pharmacyId;

    #[SerializedName('drugId')]
    public ?string $drugId;

    #[SerializedName('dosageId')]
    public ?string $dosageId;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('clinicianId')]
    public ?string $clinicianId;

    /**
     * external_case_id is an optional field that could be used to identify a prescription using an external identifier.
     */
    #[SerializedName('externalCaseId')]
    public ?string $externalCaseId;

    #[SerializedName('status')]
    public ?Status $status;

    #[SerializedName('createdAt')]
    public ?string $createdAt;

    #[SerializedName('updatedAt')]
    public ?string $updatedAt;

    /**
	 * details for the prescription from other normalized tables
 deprecated
	 */
    #[SerializedName('drugName')]
    public ?string $drugName;

    #[SerializedName('patientName')]
    public ?string $patientName;

    #[SerializedName('patientDob')]
    public ?string $patientDob;

    #[SerializedName('pharmacyName')]
    public ?string $pharmacyName;

    #[SerializedName('directions')]
    public ?string $directions;

    #[SerializedName('quantity')]
    public ?int $quantity;

    /**
     * shipping details
     */
    #[SerializedName('shippingMethod')]
    public ?PrescriptionShippingMethod $shippingMethod;

    #[SerializedName('agentId')]
    public ?string $agentId;

    #[SerializedName('dosageConcentration')]
    public ?string $dosageConcentration;

    /**
     * @var PrescriptionItem[]|null
     * list of prescription items
     */
    #[SerializedName('items')]
    public ?array $items;

    #[SerializedName('orderId')]
    public ?string $orderId;

    public function __construct(
        ?string $id = null,
        ?string $patientId = null,
        ?string $pharmacyId = null,
        ?string $drugId = null,
        ?string $dosageId = null,
        ?string $clinicId = null,
        ?string $clinicianId = null,
        ?string $externalCaseId = null,
        ?Status $status = null,
        ?string $createdAt = null,
        ?string $updatedAt = null,
        ?string $drugName = null,
        ?string $patientName = null,
        ?string $patientDob = null,
        ?string $pharmacyName = null,
        ?string $directions = null,
        ?int $quantity = null,
        ?PrescriptionShippingMethod $shippingMethod = null,
        ?string $agentId = null,
        ?string $dosageConcentration = null,
        ?array $items = [],
        ?string $orderId = null
    ) {
        $this->id = $id;
        $this->patientId = $patientId;
        $this->pharmacyId = $pharmacyId;
        $this->drugId = $drugId;
        $this->dosageId = $dosageId;
        $this->clinicId = $clinicId;
        $this->clinicianId = $clinicianId;
        $this->externalCaseId = $externalCaseId;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->drugName = $drugName;
        $this->patientName = $patientName;
        $this->patientDob = $patientDob;
        $this->pharmacyName = $pharmacyName;
        $this->directions = $directions;
        $this->quantity = $quantity;
        $this->shippingMethod = $shippingMethod;
        $this->agentId = $agentId;
        $this->dosageConcentration = $dosageConcentration;
        $this->items = $items;
        $this->orderId = $orderId;
    }
}
