<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PrescriptionItem
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('prescriptionId')]
    public ?string $prescriptionId;

    /**
     * external_id is an optional field that could be used to identify a prescription item using an external identifier.
     */
    #[SerializedName('externalId')]
    public ?string $externalId;

    #[SerializedName('drugId')]
    public string $drugId;

    #[SerializedName('dosageId')]
    public string $dosageId;

    #[SerializedName('quantity')]
    public int $quantity;

    #[SerializedName('directions')]
    public string $directions;

    #[SerializedName('drugName')]
    public ?string $drugName;

    #[SerializedName('dosageConcentration')]
    public ?string $dosageConcentration;

    #[SerializedName('daysSupply')]
    public int $daysSupply;

    #[SerializedName('shipmentDetails')]
    public ?Shipment $shipmentDetails;

    #[SerializedName('shippingMethod')]
    public ?PrescriptionItemShippingMethod $shippingMethod;

    #[SerializedName('createdAt')]
    public ?string $createdAt;

    #[SerializedName('updatedAt')]
    public ?string $updatedAt;

    #[SerializedName('orderId')]
    public ?string $orderId;

    #[SerializedName('prescriptionStatus')]
    public ?PrescriptionStatus $prescriptionStatus;

    #[SerializedName('patientId')]
    public ?string $patientId;

    #[SerializedName('pharmacyId')]
    public ?string $pharmacyId;

    #[SerializedName('pharmacyName')]
    public ?string $pharmacyName;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('clinicianId')]
    public ?string $clinicianId;

    #[SerializedName('agentId')]
    public ?string $agentId;

    #[SerializedName('justification')]
    public ?string $justification;

    #[SerializedName('totalRefills')]
    public int $totalRefills;

    #[SerializedName('patientName')]
    public ?string $patientName;

    #[SerializedName('patientDob')]
    public ?string $patientDob;

    public function __construct(
    string $drugId,
    string $dosageId,
    int $quantity,
    string $directions,
    int $daysSupply,
    int $totalRefills,
    ?string $id = null,
    ?string $prescriptionId = null,
    ?string $externalId = null,
    ?string $drugName = null,
    ?string $dosageConcentration = null,
    ?Shipment $shipmentDetails = null,
    ?PrescriptionItemShippingMethod $shippingMethod = null,
    ?string $createdAt = null,
    ?string $updatedAt = null,
    ?string $orderId = null,
    ?PrescriptionStatus $prescriptionStatus = null,
    ?string $patientId = null,
    ?string $pharmacyId = null,
    ?string $pharmacyName = null,
    ?string $clinicId = null,
    ?string $clinicianId = null,
    ?string $agentId = null,
    ?string $justification = null,
    ?string $patientName = null,
    ?string $patientDob = null
    ) {
        $this->drugId = $drugId;
        $this->dosageId = $dosageId;
        $this->quantity = $quantity;
        $this->directions = $directions;
        $this->daysSupply = $daysSupply;
    $this->totalRefills = $totalRefills;
    $this->id = $id;
    $this->prescriptionId = $prescriptionId;
    $this->externalId = $externalId;
    $this->drugName = $drugName;
    $this->dosageConcentration = $dosageConcentration;
        $this->shipmentDetails = $shipmentDetails;
        $this->shippingMethod = $shippingMethod;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->orderId = $orderId;
        $this->prescriptionStatus = $prescriptionStatus;
        $this->patientId = $patientId;
        $this->pharmacyId = $pharmacyId;
        $this->pharmacyName = $pharmacyName;
        $this->clinicId = $clinicId;
        $this->clinicianId = $clinicianId;
        $this->agentId = $agentId;
        $this->justification = $justification;
        $this->patientName = $patientName;
        $this->patientDob = $patientDob;
    }
}
