<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PreviewOrderSummaryResponse
{
    /**
     * @var LineItemPreview[]|null
     */
    #[SerializedName('lineItems')]
    public ?array $lineItems;

    #[SerializedName('subtotal')]
    public ?float $subtotal;

    #[SerializedName('total')]
    public ?float $total;

    #[SerializedName('shipping')]
    public ?Shipping $shipping;

    /**
     * Deprecated: use convenience_fee instead
     */
    #[SerializedName('creditCardFee')]
    public ?float $creditCardFee;

    #[SerializedName('convenienceFee')]
    public ?float $convenienceFee;

    public function __construct(
        ?array $lineItems = [],
        ?float $subtotal = null,
        ?float $total = null,
        ?Shipping $shipping = null,
        ?float $creditCardFee = null,
        ?float $convenienceFee = null
    ) {
        $this->lineItems = $lineItems;
        $this->subtotal = $subtotal;
        $this->total = $total;
        $this->shipping = $shipping;
        $this->creditCardFee = $creditCardFee;
        $this->convenienceFee = $convenienceFee;
    }
}
