<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PublicKey
{
    #[SerializedName('id')]
    public ?string $id;

    #[SerializedName('tenant')]
    public string $tenant;

    #[SerializedName('clinicianId')]
    public string $clinicianId;

    #[SerializedName('pem')]
    public string $pem;

    #[SerializedName('alias')]
    public string $alias;

    #[SerializedName('createdAt')]
    public ?string $createdAt;

    #[SerializedName('deletedAt')]
    public ?string $deletedAt;

    public function __construct(
        ?string $id = null,
        string $tenant,
        string $clinicianId,
        string $pem,
        string $alias,
        ?string $createdAt = null,
        ?string $deletedAt = null
    ) {
        $this->id = $id;
        $this->tenant = $tenant;
        $this->clinicianId = $clinicianId;
        $this->pem = $pem;
        $this->alias = $alias;
        $this->createdAt = $createdAt;
        $this->deletedAt = $deletedAt;
    }
}
