<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ServicesCreateAddressForTenantRequest
{
    #[SerializedName('address')]
    public ?Address $address;

    public function __construct(?Address $address = null)
    {
        $this->address = $address;
    }
}
