<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ServicesUpdateRequest
{
    #[SerializedName('patient')]
    public ?Patient $patient;

    public function __construct(?Patient $patient = null)
    {
        $this->patient = $patient;
    }
}
