<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Session
{
    #[SerializedName('access_token')]
    public string $accessToken;

    #[SerializedName('expires_at')]
    public string $expiresAt;

    public function __construct(string $accessToken, string $expiresAt)
    {
        $this->accessToken = $accessToken;
        $this->expiresAt = $expiresAt;
    }
}
