<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class SetUserPrivateKeyRequest
{
    #[SerializedName('encryptedPrivateKey')]
    public ?string $encryptedPrivateKey;

    #[SerializedName('encryptedWrapperKey')]
    public ?string $encryptedWrapperKey;

    /**
     * @var string[]|null
     */
    #[SerializedName('encryptedRecoveryKeys')]
    public ?array $encryptedRecoveryKeys;

    #[SerializedName('publicKey')]
    public ?string $publicKey;

    public function __construct(
        ?string $encryptedPrivateKey = null,
        ?string $encryptedWrapperKey = null,
        ?array $encryptedRecoveryKeys = [],
        ?string $publicKey = null
    ) {
        $this->encryptedPrivateKey = $encryptedPrivateKey;
        $this->encryptedWrapperKey = $encryptedWrapperKey;
        $this->encryptedRecoveryKeys = $encryptedRecoveryKeys;
        $this->publicKey = $publicKey;
    }
}
