<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum SexAtBirth: string
{
    case SexMale = 'SEX_MALE';
    case SexFemale = 'SEX_FEMALE';
    case SexIntersex = 'SEX_INTERSEX';
}
