<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Shipment
{
    /**
     * e.g., "FedEx", "UPS"
     */
    #[SerializedName('carrier')]
    public ?string $carrier;

    #[SerializedName('trackingUrl')]
    public ?string $trackingUrl;

    #[SerializedName('trackingNumber')]
    public ?string $trackingNumber;

    public function __construct(?string $carrier = null, ?string $trackingUrl = null, ?string $trackingNumber = null)
    {
        $this->carrier = $carrier;
        $this->trackingUrl = $trackingUrl;
        $this->trackingNumber = $trackingNumber;
    }
}
