<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ShippingFee
{
    #[SerializedName('tenant')]
    public ?string $tenant;

    #[SerializedName('clinicId')]
    public ?string $clinicId;

    #[SerializedName('shippingMethod')]
    public ?ShippingFeeShippingMethod $shippingMethod;

    #[SerializedName('feeAmount')]
    public ?float $feeAmount;

    #[SerializedName('pharmacyId')]
    public ?string $pharmacyId;

    public function __construct(
        ?string $tenant = null,
        ?string $clinicId = null,
        ?ShippingFeeShippingMethod $shippingMethod = null,
        ?float $feeAmount = null,
        ?string $pharmacyId = null
    ) {
        $this->tenant = $tenant;
        $this->clinicId = $clinicId;
        $this->shippingMethod = $shippingMethod;
        $this->feeAmount = $feeAmount;
        $this->pharmacyId = $pharmacyId;
    }
}
