<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Shipping
{
    #[SerializedName('total')]
    public ?float $total;

    public function __construct(?float $total = null)
    {
        $this->total = $total;
    }
}
