<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum Status: string
{
    case PrescriptionStatusUnspecified = 'PRESCRIPTION_STATUS_UNSPECIFIED';
    case PrescriptionStatusReceived = 'PRESCRIPTION_STATUS_RECEIVED';
    case PrescriptionStatusShipped = 'PRESCRIPTION_STATUS_SHIPPED';
    case PrescriptionStatusDelivered = 'PRESCRIPTION_STATUS_DELIVERED';
    case PrescriptionStatusCancelled = 'PRESCRIPTION_STATUS_CANCELLED';
    case PrescriptionStatusQueued = 'PRESCRIPTION_STATUS_QUEUED';
    case PrescriptionStatusUnknown = 'PRESCRIPTION_STATUS_UNKNOWN';
}
