<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class SubmitPrescriptionResponse
{
    #[SerializedName('prescription')]
    public ?Prescription $prescription;

    public function __construct(?Prescription $prescription = null)
    {
        $this->prescription = $prescription;
    }
}
