<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class SubmitExternalOrderResponse
{
    #[SerializedName('order')]
    public ?Order $order;

    public function __construct(?Order $order = null)
    {
        $this->order = $order;
    }
}
