<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Token
{
    /**
     * Unique identifier for the token
     */
    #[SerializedName('id')]
    public string $id;

    /**
     * The tenant this token belongs to
     */
    #[SerializedName('tenantId')]
    public string $tenantId;

    /**
     * The clinic this API key is scoped to
     */
    #[SerializedName('clinicId')]
    public ?string $clinicId;

    /**
     * Human-readable name for the token
     */
    #[SerializedName('name')]
    public string $name;

    /**
     * Optional description of the token's purpose
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * ID of the user who created this token
     */
    #[SerializedName('createdByUserId')]
    public ?string $createdByUserId;

    /**
     * When the token was created
     */
    #[SerializedName('createdAt')]
    public string $createdAt;

    public function __construct(
        string $id,
        string $tenantId,
        ?string $clinicId = null,
        string $name,
        ?string $description = null,
        ?string $createdByUserId = null,
        string $createdAt
    ) {
        $this->id = $id;
        $this->tenantId = $tenantId;
        $this->clinicId = $clinicId;
        $this->name = $name;
        $this->description = $description;
        $this->createdByUserId = $createdByUserId;
        $this->createdAt = $createdAt;
    }
}
