<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateClinicianResponse
{
    #[SerializedName('clinician')]
    public ?Clinician $clinician;

    public function __construct(?Clinician $clinician = null)
    {
        $this->clinician = $clinician;
    }
}
