<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateClinicResponse
{
    #[SerializedName('clinic')]
    public ?Clinic $clinic;

    public function __construct(?Clinic $clinic = null)
    {
        $this->clinic = $clinic;
    }
}
