<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class User
{
    #[SerializedName('id')]
    public string $id;

    #[SerializedName('firstName')]
    public string $firstName;

    #[SerializedName('lastName')]
    public string $lastName;

    #[SerializedName('email')]
    public string $email;

    #[SerializedName('phone')]
    public ?string $phone;

    /**
     * @var string[]|null
     */
    #[SerializedName('roles')]
    public ?array $roles;

    /**
	 * The user's private key must be encrypted using the wrapper key following the recommended encryption standards.
 The encrypted private key is only stored in the database, allowing the client to fetch the private key
 and decrypt its content using the wrapper key when needing to sign messages.
	 */
    #[SerializedName('privateKey')]
    public ?string $privateKey;

    /**
	 * The user's encrypted wrapper key has to be encrypted following the recommended encryption standards
 and encrypted on the client's device. The encrypted wrapper key is only stored in the database,
 allowing the client to fetch the wrapper key and decrypt its content when needing to sign messages.
	 */
    #[SerializedName('wrapperKey')]
    public ?string $wrapperKey;

    /**
	 * @var string[]|null
	 * Recovery keys are randomly generated and used to encrypt the user's wrapper key.
 These encrypted recovery keys are stored and can be used to recover the user's private key if access is lost.
	 */
    #[SerializedName('recoveryKeys')]
    public ?array $recoveryKeys;

    #[SerializedName('createdAt')]
    public ?string $createdAt;

    public function __construct(
        string $id,
        string $firstName,
        string $lastName,
        string $email,
        ?string $phone = null,
        ?array $roles = [],
        ?string $privateKey = null,
        ?string $wrapperKey = null,
        ?array $recoveryKeys = [],
        ?string $createdAt = null
    ) {
        $this->id = $id;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->phone = $phone;
        $this->roles = $roles;
        $this->privateKey = $privateKey;
        $this->wrapperKey = $wrapperKey;
        $this->recoveryKeys = $recoveryKeys;
        $this->createdAt = $createdAt;
    }
}
