<?php

// This file was generated by liblab | https://liblab.com/

namespace WellSyncServicesCareConnect\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Weight
{
    #[SerializedName('kg')]
    public ?float $kg;

    #[SerializedName('lbs')]
    public ?float $lbs;

    public function __construct(?float $kg = null, ?float $lbs = null)
    {
        $this->kg = $kg;
        $this->lbs = $lbs;
    }
}
