<?php

// This file was generated by liblab | https://liblab.com/

declare(strict_types=1);

namespace WellSyncServicesCareConnect;

use WellSyncServicesCareConnect\Services;

class Client
{
    public $pharmacy;
    public $billingServices;
    public $patients;
    public $sessions;
    public $tokens;

    public function __construct(
        string $accessToken,
        string $tokenPrefix = 'Bearer ',
        string $environment = Environment::Default,
        float $timeout = 0
    ) {
        $this->pharmacy = new Services\Pharmacy($accessToken, $tokenPrefix, $environment, $timeout);
        $this->billingServices = new Services\BillingServices($accessToken, $tokenPrefix, $environment, $timeout);
        $this->patients = new Services\Patients($accessToken, $tokenPrefix, $environment, $timeout);
        $this->sessions = new Services\Sessions($accessToken, $tokenPrefix, $environment, $timeout);
        $this->tokens = new Services\Tokens($accessToken, $tokenPrefix, $environment, $timeout);
    }

    public function setBaseUrl(string $url)
    {
        $this->pharmacy->setBaseUrl($url);
        $this->billingServices->setBaseUrl($url);
        $this->patients->setBaseUrl($url);
        $this->sessions->setBaseUrl($url);
        $this->tokens->setBaseUrl($url);
    }

    public function setAccessToken(string $accessToken)
    {
        $this->pharmacy->setAccessToken($accessToken);
        $this->billingServices->setAccessToken($accessToken);
        $this->patients->setAccessToken($accessToken);
        $this->sessions->setAccessToken($accessToken);
        $this->tokens->setAccessToken($accessToken);
    }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
